# Generated by Django 3.2.5 on 2022-04-17 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_myuuidmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUUIDModel',
        ),
    ]
